// After `next build` (and flatten-segments): writes out/sw.js, the service worker that keeps the
// whole app in the browser's cache so it opens and works offline (the planners themselves are
// already in the browser, in IndexedDB). It lists every file of the build under its URL, and its
// version is a hash of those files, so each new build replaces the cache in one piece.
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const out = fileURLToPath(new URL('../out', import.meta.url));

function* files(dir) {
  for (const name of readdirSync(dir).sort()) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) yield* files(path);
    else yield path;
  }
}

/** The URL a file is served at: `en/editor.html` → `/en/editor`, `index.html` → `/`. */
const urlOf = (parts) => {
  const path = parts.join('/');
  if (path === 'index.html') return '/';
  if (path.endsWith('.html') && path !== '404.html') return `/${path.slice(0, -'.html'.length)}`;
  return `/${path}`;
};

const hash = createHash('sha256');
const urls = [];
for (const file of files(out)) {
  const parts = relative(out, file).split(sep);
  const name = parts.at(-1);
  // Host configuration, the worker itself, and the nested copies of route prefetch data that
  // flatten-segments duplicated under the dotted names the client actually requests.
  if (name === '_headers' || name === 'sw.js') continue;
  if (parts.slice(0, -1).some((p) => p.startsWith('__next.'))) continue;
  urls.push(urlOf(parts));
  hash.update(urlOf(parts)).update(readFileSync(file));
}
const version = hash.digest('hex').slice(0, 12);

const worker = `// Generated by apps/web/scripts/build-sw.mjs; do not edit.
const CACHE = 'yapco-${version}';
const FILES = ${JSON.stringify(urls)};

// Keep the whole app, then take over at once.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(FILES))
      .then(() => self.skipWaiting()),
  );
});

// Drop earlier versions, so pages never mix files from two builds.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k.startsWith('yapco-') && k !== CACHE).map((k) => caches.delete(k)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

// The app from the cache (query strings such as ?id= are the app's own, not other files); the
// PDF service, the documentation (/docs) and anything not in the build from the network.
self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/docs')) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const path = url.pathname.length > 1 ? url.pathname.replace(/\\/$/, '') : url.pathname;
      const hit = await cache.match(path, { ignoreSearch: true });
      if (hit) return hit;
      try {
        return await fetch(request);
      } catch (error) {
        if (request.mode === 'navigate') {
          const missing = await cache.match('/404.html');
          if (missing) return missing;
        }
        throw error;
      }
    })(),
  );
});
`;
writeFileSync(join(out, 'sw.js'), worker);
console.log(`build-sw: ${urls.length} files, version ${version}`);
